cards_list:
- Infernal_Reckoning
- Strangling_Spores
- Detection_Tower
- Satyr_Enchanter
- Talons_of_Wildwood
- Bone_to_Ash
- Forest
- Pelakka_Wurm
- Sparktongue_Dragon
- One_with_the_Machine
- Desecrated_Tomb
- Stitcher's_Supplier
- Inspired_Charge
- Phylactery_Lich
- Dismissive_Pyromancer
- Sovereign's_Bite
- Leonin_Warleader
- Ajani's_Welcome
- Thud
- Hieromancer's_Cage
- Sift
- Skeleton_Archer
- Loxodon_Line_Breaker
- Vaevictis_Asmadi_the_Dire
- Open_the_Graves
- Blanchwood_Armor
- Knight's_Pledge
- Cleansing_Nova
- Mighty_Leap
- Blood_Divination
- Cancel
- Frilled_Sea_Serpent
- Divination
- Bristling_Boar
- Graveyard_Marshal
- Oakenform
- Liliana_Untouched_by_Death
- Sarkhan's_Unsealing
- Macabre_Waltz
- Skilled_Animator
- Aether_Tunnel
- Greenwood_Sentinel
- Millstone
- Tormenting_Voice
- Dragon's_Hoard
- Isolate
- Goblin_Motivator
- Guttersnipe
- Sure_Strike
- Essence_Scatter
- Invoke_the_Divine
- Walking_Corpse
- Fiery_Finish
- Plains
- Goblin_Trashmaster
- Recollect
- Rise_from_the_Grave
- Reliquary_Tower
- Angel_of_the_Dawn
- Submerged_Boneyard
- Gearsmith_Prodigy
- Departed_Deckhand
- Mentor_of_the_Meek
- Supreme_Phantom
- Lathliss_Dragon_Queen
- Sarkhan_Fireblood
- Aviation_Pioneer
- Electrify
- Murder
- Herald_of_Faith
- Skyrider_Patrol
- Salvager_of_Secrets
- Aven_Wind_Mage
- Dwarven_Priest
- Liliana's_Contract
- Snapping_Drake
- Manalith
- Highland_Game
- Epicure_of_Blood
- Uncomfortable_Chill
- Rabid_Bite
- Aerial_Engineer
- Banefire
- Djinn_of_Wishes
- Elvish_Clancaller
- Act_of_Treason
- Fell_Specter
- Skymarch_Bloodletter
- Vigilant_Baloth
- Timber_Gorge
- Colossal_Dreadmaw
- Colossal_Majesty
- Star-Crowned_Stag
- Psychic_Corrosion
- Gallant_Cavalry
- Boggart_Brute
- Leonin_Vanguard
- Inferno_Hellion
- Cavalry_Drillmaster
- Rhox_Oracle
- Revitalize
- Druid_of_the_Cowl
- Ghostform
- Stone_Quarry
- Duress
- Lava_Axe
- Tranquil_Expanse
- Fire_Elemental
- Explosive_Apparatus
- Mystic_Archaeologist
- Mind_Rot
- Lightning_Mare
- Remorseful_Cleric
- Cinder_Barrens
- Crucible_of_Worlds
- Declare_Dominance
- Highland_Lake
- Swamp
- Ajani's_Last_Stand
- Demanding_Dragon
- Wall_of_Mist
- Exclusion_Mage
- Surge_Mare
- Tolarian_Scholar
- Enigma_Drake
- Doublecast
- Mountain
- Shock
- Oreskos_Swiftclaw
- Fraying_Omnipotence
- Vampire_Sovereign
- Arcane_Encyclopedia
- Druid_of_Horns
- Goreclaw_Terror_of_Qal_Sisma
- Draconic_Disciple
- Rustwing_Falcon
- Catalyst_Elemental
- Centaur_Courser
- Bogstomper
- Anticipate
- Reclamation_Sage
- Nightmare's_Thirst
- Nicol_Bolas_the_Ravager
- Tezzeret_Artifice_Master
- Pegasus_Courser
- Prodigious_Growth
- Trumpet_Blast
- Take_Vengeance
- Disperse
- Suncleanser
- Palladia-Mors_the_Ruiner
- Reassembling_Skeleton
- Switcheroo
- Luminous_Bonds
- Vine_Mare
- Thorn_Lieutenant
- Giant_Spider
- Smelt
- Siegebreaker_Giant
- Meandering_River
- Novice_Knight
- Meteor_Golem
- Aegis_of_the_Heavens
- Lich's_Caress
- Doomed_Dissenter
- Ajani's_Pridemate
- Daybreak_Chaplain
- Mistcaller
- Shield_Mare
- Root_Snare
- Field_Creeper
- Demon_of_Catastrophes
- Gift_of_Paradise
- Crash_Through
- Suspicious_Bookcase
- Gargoyle_Sentinel
- Psychic_Symbiont
- Infernal_Scarring
- Vivien's_Invocation
- Death_Baron
- Island
- Militia_Bugler
- Metamorphic_Alteration
- Two-Headed_Zombie
- Regal_Bloodlord
- Heroic_Reinforcements
- Magistrate's_Scepter
- Fountain_of_Renewal
- Dragon_Egg
- Forsaken_Sanctuary
- Rupture_Spire
- Make_a_Stand
- Volcanic_Dragon
- Chaos_Wand
- Horizon_Scholar
- Knight_of_the_Tusk
- Foul_Orchard
- Dwindle
- Scholar_of_Stars
- Dark-Dweller_Oracle
- Titanic_Growth
- Hostile_Minotaur
- Diregraf_Ghoul
- Volley_Veteran
- Woodland_Stream
- Ravenous_Harpy
- Ajani_Adversary_of_Tyrants
- Tectonic_Rift
- Spit_Flame
- Vampire_Neonate
- Sigiled_Sword_of_Valeron
- Ghirapur_Guide
- Lightning_Strike
- Skyscanner
- Bone_Dragon
- Amulet_of_Safekeeping
- Apex_of_Power
- Knightly_Valor
- Naturalize
- Ghastbark_Twins
- Viashino_Pyromancer
- Goblin_Instigator
- Resplendent_Angel
- Isareth_the_Awakener
- Arcades_the_Strategist
- Thornhide_Wolves
- Gigantosaurus
- Dryad_Greenseeker
- Totally_Lost
- Plague_Mare
- Onakke_Ogre
- Mirror_Image
- Lena_Selfless_Champion
- Diamond_Mare
- Gravedigger
- Patient_Rebuilding
- Rogue's_Gloves
- Havoc_Devils
- Alpine_Moon
- Valiant_Knight
- Runic_Armasaur
- Infectious_Horror
- Windreader_Sphinx
- Marauder's_Axe
- Trusty_Packbeast
- Chromium_the_Mutable
- Daggerback_Basilisk
- Hungering_Hydra
- Gearsmith_Guardian
- Wall_of_Vines
- Plummet
- Poison-Tip_Archer
- Sai_Master_Thopterist
- Child_of_Night
- Hired_Blade
- Vivien_Reid
- Omenspeaker
- Abnormal_Endurance
- Scapeshift
- Omniscience
- Sleep
- Aethershield_Artificer
- Elvish_Rejuvenator
- Brawl-Bash_Ogre
- Transmogrifying_Wand